### ISSUE TITLE
crash when trying to save GPX (no gapps)

### ISSUE THREAD

**Issue by soratobukuroneko** [y20k/trackbook#70]
Hi, I have no gapp but microG. When I open a track and on the map view touch the save icon on the bottom right the application crash. Here the logcat:
```
--------- beginning of crash
04-01 16:22:53.354 31017 31017 E AndroidRuntime: FATAL EXCEPTION: main
04-01 16:22:53.354 31017 31017 E AndroidRuntime: Process: org.y20k.trackbook, PID: 31017
04-01 16:22:53.354 31017 31017 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/gpx+xml (has extras) }
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4587)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at h.k.d.d.startActivityForResult(Unknown Source:10)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at h.h.d.a.a(Unknown Source:0)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at h.k.d.d$a.a(:1)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at org.y20k.trackbook.TrackFragment.b(:2)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at org.y20k.trackbook.TrackFragment$a.onClick(java-style lambda group:20)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at android.view.View.performClick(View.java:6597)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6574)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25906)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-01 16:22:53.354 31017 31017 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-01 16:22:53.380 31017 31017 I Process : Sending signal. PID: 31017 SIG: 9
```

**Comment by y20k** [comment]
Thank you for the report. I don't get this crash on my device (LineageOS for microG 16.0). At this point my speculation would be: Maybe your device has no file manager? Could you provide some more details?

- which OS version?
- which file manager installed?
- do you see a file picker before the crash happens?

After tapping the save icon this system dialog should appear:
![Screenshot_20200401-170349_Files](https://user-images.githubusercontent.com/9103935/78153164-14dad680-743b-11ea-8771-d7fa0db7a986.png)

**Comment by soratobukuroneko** [comment]
LineageOS 16.0. Found the issue, I had the default file manager disabled has I use Ghost Commander. Enabling it again solves the issue.

**Comment by y20k** [comment]
Thanks. I added a check, if a file manager is present on the device. I hope that would prevent a crash.

**Comment by jwmh** [comment]
I'm also having it crash.
App version is latest currently on FDroid:  
Android GO,  8.1.0
Stock ROM,  NOT rooted.
Make: Hot Pepper
Model: Poblano
Model#:  VLE5
(Yes, this is a cheap phone.)
